- hosts: server
  vars:
     image : andre17723/docker-ansible:beta
  tasks: 
   - name: install python-docker ubuntu
     apt: 
       name: python-docker
       state: present
     when:
     - ansible_distribution == "Ubuntu"
   - name: pull image
     docker_image:
       name: "{{ image }}"
       state: present
       force: yes
   - name: create container
     docker_container:
       recreate: yes
       name: docker_ansible
       state: started
       image: "{{ image }}"
       exposed_ports:
       - 8090:80
       published_ports:
       - 8090:80
  
